export const state_options = [
    { value: 'alabama', label: 'Alabama' },
    { value: 'alaska', label: 'Alaska' },
    { value: 'american samoa', label: 'American Samoa' },
    { value: 'arizona', label: 'Arizona' },
    { value: 'arkansas', label: 'Arkansas' },
    { value: 'california', label: 'California' },
    { value: 'colorado', label: 'Colorado' },
    { value: 'connecticut', label: 'Connecticut' },
    { value: 'delaware', label: 'Delaware' },
    { value: 'district of columbia', label: 'District Of Columbia' },
    { value: 'federated states of micronesia', label: 'Federated States Of Micronesia' },
    { value: 'florida', label: 'Florida' },
    { value: 'georgia', label: 'Georgia' },
    { value: 'guam', label: 'Guam' },
    { value: 'hawaii', label: 'Hawaii' },
    { value: 'idaho', label: 'Idaho' },
    { value: 'illinois', label: 'Illinois' },
    { value: 'indiana', label: 'Indiana' },
    { value: 'iowa', label: 'Iowa' },
    { value: 'kansas', label: 'Kansas' },
    { value: 'kentucky', label: 'Kentucky' },
    { value: 'louisiana', label: 'Louisiana' },
    { value: 'maine', label: 'Maine' },
    { value: 'marshall islands', label: 'Marshall Islands' },
    { value: 'maryland', label: 'Maryland' },
    { value: 'massachusetts', label: 'Massachusetts' },
    { value: 'michigan', label: 'Michigan' },
    { value: 'minnesota', label: 'Minnesota' },
    { value: 'mississippi', label: 'Mississippi' },
    { value: 'missouri', label: 'Missouri' },
    { value: 'montana', label: 'Montana' },
    { value: 'nebraska', label: 'Nebraska' },
    { value: 'nevada', label: 'Nevada' },
    { value: 'new hampshire', label: 'New Hampshire' },
    { value: 'new jersey', label: 'New Jersey' },
    { value: 'new mexico', label: 'New Mexico' },
    { value: 'new york new york', label: 'NewYork NewYork' },
    { value: 'north carolina', label: 'North Carolina' },
    { value: 'north dakota', label: 'North Dakota' },
    { value: 'northern mariana islands', label: 'Northern Mariana Islands' },
    { value: 'ohio', label: 'Ohio' },
    { value: 'oklahoma', label: 'Oklahoma' },
    { value: 'oregon', label: 'Oregon' },
    { value: 'palau', label: 'Palau' },
    { value: 'pennsylvania', label: 'Pennsylvania' },
    { value: 'puerto rico', label: 'Puerto Rico' },
    { value: 'rhode island', label: 'Rhode Island' },
    { value: 'south carolina', label: 'South Carolina' },
    { value: 'south dakota', label: 'South Dakota' },
    { value: 'tennessee', label: 'Tennessee' },
    { value: 'texas', label: 'Texas' },
    { value: 'utah', label: 'Utah' },
    { value: 'vermont', label: 'Vermont' },
    { value: 'virgin islands', label: 'Virgin Islands' },
    { value: 'virginia', label: 'Virginia' },
    { value: 'washington', label: 'Washington' },
    { value: 'west virginia', label: 'West Virginia' },
    { value: 'wisconsin', label: 'Wisconsin' },
    { value: 'wyoming', label: 'Wyoming' }
  ]

export const department_options = [
  { value: 'sales', label: 'Sales' },
  { value: 'marketing', label: 'Marketing' },
  { value: 'engineering', label: 'Engineering' },
  { value: 'human resources', label: 'Human Resources' },
  { value: 'legal', label: 'Legal' }
]